const { x402Middleware } = require('@x402/vercel');

// Research endpoint - $0.10
module.exports = x402Middleware(
  { price: '$0.10', receiver: process.env.RECEIVER_WALLET },
  async (req, res) => {
    const { query } = req.body || {};
    
    if (!query) {
      return res.status(400).json({ 
        error: "Query required",
        example: { query: "What are the top yield opportunities on Solana?" }
      });
    }
    
    // Simple research responses based on query keywords
    const query_lower = query.toLowerCase();
    let research = {
      query: query,
      timestamp: new Date().toISOString(),
      disclaimer: "Research generated by AI agent - verify before acting",
      sources: ["DeFi Llama", "CoinGecko", "Protocol docs"]
    };
    
    if (query_lower.includes('yield') || query_lower.includes('apy')) {
      research.summary = "Top yield opportunities analyzed";
      research.findings = [
        "Kamino (Solana): 10% APY on USDC - Automated vaults, $100M+ TVL",
        "Moonwell (Base): 8% APY on USDC - Established protocol",
        "Solend (Solana): 6% APY on USDC - Conservative option",
        "Aerodrome (Base): 15-20% APY - Higher risk LP positions"
      ];
      research.recommendation = "For $50-100 capital: Kamino offers best risk-adjusted yield";
    } else if (query_lower.includes('x402') || query_lower.includes('agent')) {
      research.summary = "x402 agent commerce ecosystem";
      research.findings = [
        "100+ services in bazaar",
        "Pricing: $0.01-$5.00 per request",
        "Popular categories: DeFi analytics, research, sentiment",
        "Gap: Agent operations/insights underrepresented"
      ];
      research.recommendation = "Launch unique service to capture market share";
    } else {
      research.summary = "General research query processed";
      research.findings = [
        "Query received and analyzed",
        "For specific research, try keywords: yield, APY, x402, agent"
      ];
      research.recommendation = "Refine query for better results";
    }
    
    res.json(research);
  }
);